using System.Xml.Linq;

namespace Beep.Installer.Engine.ClickOnce;

/// <summary>
/// Writes a ClickOnce deployment manifest (<c>.application</c>) (Track B1.1): identity, version,
/// a <c>deployment</c> element (with an optional <c>deploymentProvider</c> update URL), and a
/// <c>dependency</c> that references the application manifest by relative path + SHA-256 digest.
/// </summary>
public static class DeploymentManifestWriter
{
    public static readonly XNamespace AsmV1 = "urn:schemas-microsoft-com:asm.v1";

    /// <param name="appManifestCodebase">Relative path to the .manifest (e.g. <c>Application\MyApp.manifest</c>).</param>
    /// <param name="appManifestDigestBase64">SHA-256 (base64) of the application manifest.</param>
    /// <param name="appManifestSize">Size in bytes of the application manifest.</param>
    public static void Write(
        string outputPath, string name, string version, string? publisher, string? description,
        string appManifestCodebase, string appManifestDigestBase64, long appManifestSize,
        string? updateUrl, bool install = true)
    {
        var root = new XElement(AsmV1 + "assembly", new XAttribute("manifestVersion", "1.0"));
        root.Add(new XElement(AsmV1 + "assemblyIdentity",
            new XAttribute("name", name),
            new XAttribute("version", ApplicationManifestWriter.NormalizeVersion(version)),
            new XAttribute("type", "application")));

        if (!string.IsNullOrWhiteSpace(description))
            root.Add(new XElement(AsmV1 + "description", description));

        var deployment = new XElement(AsmV1 + "deployment", new XAttribute("install", install ? "true" : "false"));
        if (!string.IsNullOrWhiteSpace(updateUrl))
            deployment.Add(new XElement(AsmV1 + "deploymentProvider",
                new XAttribute("codebase", updateUrl)));
        root.Add(deployment);

        var dep = new XElement(AsmV1 + "dependency");
        var dependent = new XElement(AsmV1 + "dependentAssembly",
            new XAttribute("dependencyType", "install"),
            new XAttribute("codebase", appManifestCodebase.Replace('\\', '/')),
            new XAttribute("size", appManifestSize),
            new XAttribute("hash", appManifestDigestBase64),
            new XAttribute("hashalg", "SHA256"));
        dependent.Add(new XElement(AsmV1 + "assemblyIdentity",
            new XAttribute("name", name),
            new XAttribute("version", ApplicationManifestWriter.NormalizeVersion(version)),
            new XAttribute("type", "win32")));
        dep.Add(dependent);
        root.Add(dep);

        if (!string.IsNullOrWhiteSpace(publisher))
            root.Add(new XElement(AsmV1 + "publisher", publisher));

        new XDocument(
            new XDeclaration("1.0", "utf-8", null),
            new XComment(" Generated by Beep.Installer — deployment manifest (Track B) "),
            root).Save(outputPath);
    }
}
