using System;
using System.IO;
using System.Security.Cryptography;
using System.Xml.Linq;

namespace Beep.Installer.Engine.ClickOnce;

/// <summary>
/// Writes a ClickOnce application manifest (<c>.manifest</c>) for a payload directory (Track B1.2).
/// Lists every file with its size and SHA-256 digest, and flags the entry point. Structurally
/// faithful to the ClickOnce schema; full <c>mage -Verify</c> acceptance is a later checkpoint.
/// </summary>
public static class ApplicationManifestWriter
{
    public static readonly XNamespace AsmV1 = "urn:schemas-microsoft-com:asm.v1";

    /// <summary>
    /// Writes <paramref name="outputPath"/> and returns <c>(digestBase64, sizeBytes)</c> of the
    /// written manifest (so a deployment manifest can reference it).
    /// </summary>
    public static (string digestBase64, long sizeBytes) Write(
        string payloadDir, string entryPoint, string outputPath,
        string name, string version, string? description)
    {
        var root = new XElement(AsmV1 + "assembly", new XAttribute("manifestVersion", "1.0"));
        root.Add(new XElement(AsmV1 + "assemblyIdentity",
            new XAttribute("name", name),
            new XAttribute("version", NormalizeVersion(version)),
            new XAttribute("type", "win32")));

        if (!string.IsNullOrWhiteSpace(description))
            root.Add(new XElement(AsmV1 + "description", description));

        foreach (var file in Directory.EnumerateFiles(payloadDir, "*", SearchOption.AllDirectories))
        {
            var rel = Path.GetRelativePath(payloadDir, file).Replace('\\', '/');
            var bytes = File.ReadAllBytes(file);
            root.Add(new XElement(AsmV1 + "file",
                new XAttribute("name", rel),
                new XAttribute("size", bytes.Length),
                new XAttribute("hash", Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant()),
                new XAttribute("hashalg", "SHA256")));
        }

        if (!string.IsNullOrWhiteSpace(entryPoint))
        {
            var ep = new XElement(AsmV1 + "entryPoint");
            ep.Add(new XElement(AsmV1 + "assemblyIdentity",
                new XAttribute("name", name),
                new XAttribute("version", NormalizeVersion(version))));
            ep.Add(new XElement(AsmV1 + "commandLine",
                new XAttribute("file", entryPoint),
                new XAttribute("parameters", "")));
            root.Add(ep);
        }

        new XDocument(
            new XDeclaration("1.0", "utf-8", null),
            new XComment(" Generated by Beep.Installer — application manifest (Track B) "),
            root).Save(outputPath);

        return HashOf(outputPath);
    }

    /// <summary>SHA-256 (base64) + size of a file — used by the deployment manifest reference.</summary>
    public static (string digestBase64, long sizeBytes) HashOf(string path)
    {
        var bytes = File.ReadAllBytes(path);
        using var sha = SHA256.Create();
        return (Convert.ToBase64String(sha.ComputeHash(bytes)), bytes.Length);
    }

    /// <summary>ClickOnce versions are 4-octet numeric (x.y.z[.w]); pad/truncate to four parts.</summary>
    public static string NormalizeVersion(string version)
    {
        var parts = (version ?? "1.0.0").Split('.', StringSplitOptions.RemoveEmptyEntries);
        var p = new string[4];
        for (int i = 0; i < 4; i++)
            p[i] = (i < parts.Length && int.TryParse(parts[i], out _)) ? parts[i] : "0";
        return string.Join('.', p);
    }
}
