using System;
using System.IO;
using System.Linq;
using System.Xml.Linq;

namespace Beep.Installer.Engine.ClickOnce;

/// <summary>
/// Stages a ClickOnce publish folder (Track B1.3). Copies the payload into <c>publish\Application\</c>
/// renaming every file to <c>*.deploy</c> (ClickOnce convention, undone on install), writes the
/// application manifest under <c>Application\</c> and the deployment manifest at the publish root
/// (neither manifest is renamed), and generates a <c>publish.htm</c> landing page.
/// </summary>
public static class PublishStager
{
    public static string IdentityName(string appId)
    {
        if (!Guid.TryParseExact(appId, "D", out var id) || id == Guid.Empty)
            throw new ArgumentException("ClickOnce publication requires a nonzero AppId GUID.", nameof(appId));
        return $"Beep.{id:D}";
    }

    /// <summary>Result of staging a publish folder.</summary>
    public class StageResult
    {
        public string PublishDir = "";
        public string ApplicationManifestPath = "";
        public string DeploymentManifestPath = "";
        public string PublishHtmlPath = "";
        public int DeployFiles;
    }

    /// <param name="entryPoint">Payload-relative main executable (e.g. <c>MyApp.exe</c>).</param>
    public static StageResult Stage(
        string payloadDir, string publishDir, string productName, string version,
        string? publisher, string? description, string entryPoint, string? updateUrl, string appId)
    {
        var identity = IdentityName(appId);
        if (!Directory.Exists(payloadDir)) throw new DirectoryNotFoundException(payloadDir);
        Directory.CreateDirectory(publishDir);
        var appDir = Path.Combine(publishDir, "Application");
        if (Directory.Exists(appDir)) Directory.Delete(appDir, recursive: true);
        Directory.CreateDirectory(appDir);

        // 1) Copy payload files, renaming each to *.deploy.
        int deployCount = 0;
        foreach (var file in Directory.EnumerateFiles(payloadDir, "*", SearchOption.AllDirectories))
        {
            var rel = Path.GetRelativePath(payloadDir, file);
            var dest = Path.Combine(appDir, rel + ".deploy");
            Directory.CreateDirectory(Path.GetDirectoryName(dest)!);
            File.Copy(file, dest, overwrite: true);
            deployCount++;
        }

        // 2) Application manifest under Application\ (NOT renamed).
        var appManifestPath = Path.Combine(appDir, identity + ".manifest");
        var (digest, size) = ApplicationManifestWriter.Write(
            payloadDir, entryPoint, appManifestPath, identity, version, description);

        // 3) Deployment manifest at the publish root (NOT renamed) referencing the app manifest.
        var deployManifestPath = Path.Combine(publishDir, identity + ".application");
        var codebase = $"Application/{identity}.manifest";
        DeploymentManifestWriter.Write(
            deployManifestPath, identity, version, publisher, description,
            codebase, digest, size, updateUrl);

        // 4) Landing page.
        var htmlPath = Path.Combine(publishDir, "publish.htm");
        File.WriteAllText(htmlPath, BuildPublishHtml(productName, version, publisher, identity));

        return new StageResult
        {
            PublishDir = publishDir,
            ApplicationManifestPath = appManifestPath,
            DeploymentManifestPath = deployManifestPath,
            PublishHtmlPath = htmlPath,
            DeployFiles = deployCount
        };
    }

    private static string BuildPublishHtml(string product, string version, string? publisher, string identity)
    {
        var title = System.Net.WebUtility.HtmlEncode(product);
        var pub = System.Net.WebUtility.HtmlEncode(publisher ?? "");
        var appRef = System.Net.WebUtility.HtmlEncode(identity + ".application");
        return $@"<!DOCTYPE html>
<html><head><meta charset=""utf-8""><title>{title} {System.Net.WebUtility.HtmlEncode(version)} Setup</title></head>
<body style=""font-family:Segoe UI,Arial,sans-serif;margin:40px"">
  <h1>{title}</h1>
  <p>Version {System.Net.WebUtility.HtmlEncode(version)}{ (string.IsNullOrEmpty(pub) ? "" : " — " + pub)}</p>
  <p><a href=""{appRef}"">Install {title}</a></p>
  <p style=""color:#666"">Generated by Beep.Installer (ClickOnce publish).</p>
</body></html>";
    }
}
